sudo: required 
language: python
python:
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

services:
  - docker

script:
  - echo "skipping tests"  

after_success:
  - sh deploy.sh

