sudo: required 
language: python
python:
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

services:
  - docker

script:
  - pytest 

after_success:
  - sh deploy.sh
  – test “$TRAVIS_BRANCH” = “master” && sh deploy_heroku.sh

